sudo: required
dist: trusty
group: edge

language: erlang

services:
  - docker

otp_release:
  - 19.1
  - 20.0
  - 20.1
  - 21.0

before_install:
  - sudo add-apt-repository ppa:jonathonf/curl -y
  - sudo apt-get update -q
  - sudo apt-get install curl -y

script: rebar3 update && rebar3 ct --readable=false && rebar3 dialyzer && rebar3 coveralls send

cache:
  directories:
  - $HOME/.cache/rebar3/

addons:
  apt:
    packages:
      - libevent-dev
